# 상품코드 별 매출액(판매가 x 판매량) 합계 출력
# 매출액 기준 내림차순, 상품코드 기준 오름차순
SELECT P.PRODUCT_CODE,SUM(P.PRICE * S.SALES_AMOUNT) AS SALES
FROM PRODUCT P
JOIN OFFLINE_SALE S ON S.PRODUCT_ID = P.PRODUCT_ID
GROUP BY S.PRODUCT_ID
ORDER BY SALES DESC,P.PRODUCT_CODE ASC;