-- 코드를 입력하세요
SELECT C.CAR_ID,C.CAR_TYPE,
ROUND(C.DAILY_FEE * 30 * (1-(P.DISCOUNT_RATE / 100))) AS FEE
FROM CAR_RENTAL_COMPANY_CAR C
JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN P ON P.CAR_TYPE = C.CAR_TYPE and P.DURATION_TYPE = '30일 이상'
WHERE C.CAR_TYPE IN ('SUV','세단')
AND C.CAR_ID NOT IN (
    SELECT CAR_ID
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
    WHERE START_DATE <= '2022-11-30' AND END_DATE >= '2022-11-01' # 2023-12-01 부터 시작날짜 설정 가능, 끝나는날짜 2022-10-31까지 가능하게
)
having fee >= 500000 and fee < 2000000
ORDER BY FEE DESC, C.CAR_TYPE ASC, C.CAR_ID DESC