# 2021년 가입한 전체 회원들 중
# 상품을 구매한 회원수, 상품을 구매한 회원의 비율(2021가입 중 상품 구매한 회원 수 / 2021 전체 가입 수)
# 상품 구매한 회원의 비율은 소수점 두번째자리에서 반올림
# 전체 결과는 년 오름차순, 월 오름차순
SELECT YEAR(S.SALES_DATE) AS YEAR, MONTH(S.SALES_DATE) AS MONTH,
COUNT(DISTINCT S.USER_ID) AS PURCHASED_USERS,
ROUND(
COUNT(DISTINCT S.USER_ID) / (SELECT COUNT(*) FROM USER_INFO WHERE JOINED LIKE '2021%'),1
) AS PUCHASED_RATIO
FROM USER_INFO I
JOIN ONLINE_SALE S ON S.USER_ID = I.USER_ID
WHERE I.JOINED LIKE '2021%'
GROUP BY YEAR,MONTH
ORDER BY YEAR ASC,MONTH ASC;