# 2022-5월인 식품들
# 총매출 기준으로 내림차순
# 총매출 같을 경우 id 기준 정렬
SELECT P.PRODUCT_ID,P.PRODUCT_NAME,SUM(P.PRICE*O.AMOUNT) AS TOTAL_SALES
FROM FOOD_PRODUCT P
JOIN FOOD_ORDER O ON O.PRODUCT_ID = P.PRODUCT_ID
WHERE O.PRODUCE_DATE >= '2022-05-01' AND O.PRODUCE_DATE <= '2022-05-31'
GROUP BY P.PRODUCT_ID
ORDER BY TOTAL_SALES DESC,P.PRODUCT_ID ASC;