# 리뷰를 가장 많이 작성한 회원 리뷰 조회
# 리뷰 작성일 기준 오름차순, 리뷰 텍스트 기준 오름차순
SELECT P.MEMBER_NAME,R.REVIEW_TEXT,REVIEW_DATE
FROM MEMBER_PROFILE P
JOIN REST_REVIEW R ON R.MEMBER_ID = P.MEMBER_ID
WHERE P.MEMBER_ID = (
    SELECT MEMBER_ID
    FROM REST_REVIEW
    GROUP BY MEMBER_ID
    ORDER BY COUNT(*) DESC
    LIMIT 1
)
ORDER BY R.REVIEW_DATE ASC, R.REVIEW_TEXT ASC;
