-- 코드를 작성해주세요
SELECT SUM(SCORE) AS SCORE, B.EMP_NO, B.EMP_NAME,	B.POSITION, B.EMAIL
FROM HR_GRADE A
JOIN HR_EMPLOYEES B ON A.EMP_NO = B.EMP_NO
WHERE A.YEAR = 2022
GROUP BY EMP_NO
ORDER BY SCORE DESC
LIMIT 1